### ISSUE TITLE
tests needed

### ISSUE THREAD

**Issue by leoduan** [neurodata/jkmeans#1]
- [x]  fix p=1, let n increase, get the following metrics: RMSE of mu, misclassification error of Z, etc.
- [x]  different degree of overlapping among clusters

**Comment by jovo** [comment]
:ok_hand:

On Friday, July 1, 2016, Leo Duan notifications@github.com wrote:

> -[ ] fix p=1, let n increase, get the following metrics: RMSE of mu,
> misclassification error of Z, etc.
> -[ ] different degree of overlapping among clusters
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/jkmeans/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/AACjcsZK7tGx5hCDVlP7gHcxsJWXgIRzks5qRUelgaJpZM4JDUTF
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
- [ ] include balanced case
- [ ] make k=10 or so
