### ISSUE TITLE
more theory work

### ISSUE THREAD

**Issue by leoduan** [neurodata/jkmeans#14]
- [x] Establish why (or why not) to consider the variability of the projection matrix -- via running algorithm without E step and compare.

- [x] Prove the theory that reduced dimension is advantageous over GMM in the presence of irrelevant dimension

- [x] check out theory on LOL paper

**Comment by leoduan** [comment]
@jovo

**Comment by jovo** [comment]
Solid plan.
Maybe experimentally demonstrate repulsive property too?
